export enum AssignedExamStatus {
    PENDING = 'PENDING',
    ENABLED = 'ENABLED',
    IN_EVALUATION = 'IN_EVALUATION',
    SUBMITTED = 'SUBMITTED',
    GRADED = 'GRADED',
    CANCELLED = 'CANCELLED',
}
