export enum AssignedExamStatus {
    ASSIGNED = 'ASSIGNED',
    AVAILABLE = 'AVAILABLE',
    IN_PROGRESS = 'IN_PROGRESS',
    SUBMITTED = 'SUBMITTED',
    GRADED = 'GRADED',
    RETURNED = 'RETURNED',
    EXPIRED = 'EXPIRED',
    CANCELLED = 'CANCELLED',
}
