name: Lint
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: lint-${{ github.event.pull_request.head.sha }}
  cancel-in-progress: true

jobs:
  eslint:
    name: ESLint (Node 20)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run lint -- --max-warnings=0
